#!/usr/bin/env python3
"""
Build script for ARCHived static site.

1. Runs the scraper to collect fresh data
2. Copies static assets to docs/ folder (for GitHub Pages)
3. Verifies all files are in place
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path
import logging


# Configuration
DOCS_DIR = Path("docs")
STATIC_FILES = ["index.html", "about.html", "styles.css", "app.js", "dead-projects.json"]

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")


def run_scraper():
    """Execute the scraper module in-process to avoid subprocess overhead.

    This imports the scraper and invokes its CLI function programmatically.
    If the scraper's CLI changes we fall back to invoking it as a subprocess.
    """
    logger.info("Running scraper (in-process)...")

    # Allow skipping scraper via env var for CI/debugging
    if os.environ.get('SKIP_SCRAPER', '').lower() in ('1', 'true', 'yes'):
        logger.info('SKIP_SCRAPER set; skipping scraper run')
        return True

    # Try to call the scraper module directly for better testability and to
    # avoid forking a second Python interpreter. Fall back to subprocess if
    # import fails for any reason.
    try:
        # Import here to avoid overhead when skipping
        from scraper import collect as scraper_collect

        # Use collect_projects with default values and write output via save_json
        projects, truncated = scraper_collect.collect_projects()
        scraper_collect.save_json(projects, "dead-projects.json", months=12, min_stars=10, truncated=truncated)
        return True
    except Exception as e:  # pragma: no cover - fallback path
        logger.warning("In-process scraper failed (%s). Falling back to subprocess.", e)
        try:
            result = subprocess.run([
                sys.executable,
                "scraper/collect.py",
                "--months",
                "12",
                "--min-stars",
                "10",
            ], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
            if result.stdout:
                logger.info(result.stdout)
            if result.returncode != 0:
                logger.error("Scraper subprocess failed: returncode=%s", result.returncode)
                return False
            return True
        except Exception as e2:
            logger.exception("Failed to run scraper subprocess: %s", e2)
            return False


def ensure_docs_dir():
    """Create docs directory if it doesn't exist."""
    DOCS_DIR.mkdir(exist_ok=True)
    logger.info("Ensured %s/ directory exists", DOCS_DIR)


def copy_static_files():
    """Copy all static files to docs directory."""
    logger.info("Copying static files to docs/...")
    for file in STATIC_FILES:
        src = Path(file)
        dst = DOCS_DIR / file
        if src.exists():
            shutil.copy2(src, dst)
            logger.info("  ✓ %s", file)
        else:
            # dead-projects.json is generated by the scraper and intentionally
            # not tracked in the repository. Treat its absence as a warning
            # rather than a hard failure so the build can proceed when the
            # data artifact isn't present locally.
            if file == "dead-projects.json":
                logger.warning("  ⚠ %s not found (this file is generated by the scraper). Skipping.", file)
                continue
            logger.error("  ✗ %s not found!", file)
            return False
    return True


def main():
    """Main build pipeline."""
    logger.info("%s", "=" * 60)
    logger.info("ARCHived - Site Builder")
    logger.info("%s", "=" * 60)

    # Step 1: Run scraper. If it fails, allow continuation when an existing
    # docs/ artifact already contains dead-projects.json (use last-known
    # generated data to avoid blocking deployments on transient scraper/GitHub
    # API issues). If neither exists, treat as a hard failure.
    scraper_ok = run_scraper()

    # If scraper failed, try to fall back to docs/dead-projects.json
    if not scraper_ok:
        logger.warning("Scraper failed; attempting to proceed using existing docs/ artifact if present")

    # Check that dead-projects.json was created at the repository root. If not,
    # fall back to docs/dead-projects.json (copy it to the root) so CI steps
    # that expect dead-projects.json at the workspace root (upload-artifact)
    # still work.
    root_dead = Path("dead-projects.json")
    docs_dead = DOCS_DIR / "dead-projects.json"

    if not root_dead.exists():
        if docs_dead.exists():
            logger.warning("root dead-projects.json missing — copying %s -> %s", docs_dead, root_dead)
            try:
                shutil.copy2(docs_dead, root_dead)
            except Exception as e:
                logger.exception("Failed to copy fallback dead-projects.json: %s", e)
                return 1
        else:
            logger.error("dead-projects.json not generated and no fallback found in %s", DOCS_DIR)
            return 1

    # Step 2: Prepare docs directory
    ensure_docs_dir()

    # Step 3: Copy static files
    if not copy_static_files():
        return 1

    logger.info("%s", "\n" + "=" * 60)
    logger.info("✓ Build complete!")
    logger.info("%s", "=" * 60)
    logger.info("The site is ready in the '%s/' folder.", DOCS_DIR)
    logger.info("To preview locally:")
    logger.info("  python -m http.server 8000 --directory docs")
    logger.info("Push to GitHub to deploy:")
    logger.info("  git add docs/")
    logger.info("  git commit -m 'Update dead projects'")
    logger.info("  git push")

    return 0


if __name__ == "__main__":
    sys.exit(main())
