#!/usr/bin/env python3
"""
Build script for ARCHived static site.

1. Runs the scraper to collect fresh data
2. Copies static assets to docs/ folder (for GitHub Pages)
3. Verifies all files are in place
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path
import logging


# Configuration
DOCS_DIR = Path("docs")
STATIC_FILES = ["index.html", "about.html", "styles.css", "app.js", "dead-projects.json"]

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")


def run_scraper():
    """Execute the scraper script to generate fresh data."""
    logger.info("Running scraper...")
    # Run scraper with defaults; allow collect.py to accept CLI args in the future
    # Allow skipping scraper for faster CI/debugging via env var
    if os.environ.get('SKIP_SCRAPER', '').lower() in ('1', 'true', 'yes'):
        logger.info('SKIP_SCRAPER set; skipping scraper run')
        return True

    # We intentionally use subprocess.run with an explicit argv list (no
    # shell=True) to execute the scraper in a separate process. This is
    # done to preserve the existing execution environment and to keep the
    # build tool simple. The arguments are static and not derived from
    # untrusted input, so the risk of command injection is minimal.
    #
    # Bandit flags subprocess usage as a warning (B404/B603). If you prefer,
    # we can call the scraper's main function directly to avoid spawning a
    # new process.
    result = subprocess.run([
        sys.executable,
        "scraper/collect.py",
        "--months",
        "12",
        "--min-stars",
        "10",
    ], capture_output=True, text=True)

    if result.stdout:
        logger.info(result.stdout)
    if result.stderr:
        logger.warning("STDERR: %s", result.stderr)

    if result.returncode != 0:
        logger.error("Scraper failed!")
        return False

    return True


def ensure_docs_dir():
    """Create docs directory if it doesn't exist."""
    DOCS_DIR.mkdir(exist_ok=True)
    logger.info("Ensured %s/ directory exists", DOCS_DIR)


def copy_static_files():
    """Copy all static files to docs directory."""
    logger.info("Copying static files to docs/...")
    for file in STATIC_FILES:
        src = Path(file)
        dst = DOCS_DIR / file
        if src.exists():
            shutil.copy2(src, dst)
            logger.info("  ✓ %s", file)
        else:
            # dead-projects.json is generated by the scraper and intentionally
            # not tracked in the repository. Treat its absence as a warning
            # rather than a hard failure so the build can proceed when the
            # data artifact isn't present locally.
            if file == "dead-projects.json":
                logger.warning("  ⚠ %s not found (this file is generated by the scraper). Skipping.", file)
                continue
            logger.error("  ✗ %s not found!", file)
            return False
    return True


def main():
    """Main build pipeline."""
    logger.info("%s", "=" * 60)
    logger.info("ARCHived - Site Builder")
    logger.info("%s", "=" * 60)

    # Step 1: Run scraper
    if not run_scraper():
        return 1

    # Check that dead-projects.json was created
    if not Path("dead-projects.json").exists():
        logger.error("dead-projects.json not generated!")
        return 1

    # Step 2: Prepare docs directory
    ensure_docs_dir()

    # Step 3: Copy static files
    if not copy_static_files():
        return 1

    logger.info("%s", "\n" + "=" * 60)
    logger.info("✓ Build complete!")
    logger.info("%s", "=" * 60)
    logger.info("The site is ready in the '%s/' folder.", DOCS_DIR)
    logger.info("To preview locally:")
    logger.info("  python -m http.server 8000 --directory docs")
    logger.info("Push to GitHub to deploy:")
    logger.info("  git add docs/")
    logger.info("  git commit -m 'Update dead projects'")
    logger.info("  git push")

    return 0


if __name__ == "__main__":
    sys.exit(main())
